### ISSUE TITLE
Splash Screen

### ISSUE THREAD

**Issue by HenryRA07** [HenryRA07/Proyecto-WebSite-News#11]
## Código Html
```html
<!-- Splash Screen -->
<div id="splash">
        <video id="splash-video" autoplay muted playsinline>
            <source src="/img/Digital Cam (2).mp4" type="video/mp4">
            Tu navegador no soporta el video.
        </video>
    </div>
``` 

## Código CSS
```css
/*Estilos para hacer un slpash screen con palabras*/
        /* Estilos del splash screen */
        #splash {
            position: fixed;
            width: 100%;
            height: 100vh;
            background-color: #ffffff;
            color: white;
            display: flex;
            justify-content: center;
            align-items: center;
            z-index: 1000;
            transition: opacity 1s ease;

            /*Codigo agregado para que se desvanezca*/
            opacity: 1;
            visibility: visible;
            transition: opacity 1s ease, visibility 0s 1s; /* El tiempo de transición puede ajustarse */

        }

        .splash-content h1 {
            font-size: 3rem;
        }

        /*Codigo agregado para que se desvanezca*/
        #splash.hidden {
            opacity: 0;
            visibility: hidden;
            transition: opacity 1s ease, visibility 0s 1s;
        }
        /*00000*/

        .splash-content p {
            font-size: 1.2rem;
        }

        /* Ocultar el contenido principal mientras el splash está activo */
        #main-content {
            display: none;
        }

        /* Mostrar el contenido principal una vez que el splash desaparece */
        .show-content #main-content {
            display: block;
        }

``` 

## Código JS
```javascript
//Codigo de Splash Screen
        window.addEventListener("load", function() {
            // Simula una carga de contenido (puedes personalizar el tiempo)
            setTimeout(function() {
                document.getElementById('splash').classList.add('hidden');
                document.body.classList.add('show-content');
            }, 2000); // El splash dura 2 segundos antes de empezar a desvanecerse
        });

window.addEventListener("load", function() {
    var video = document.getElementById('splash-video');
    video.onended = function() {
        document.getElementById('splash').classList.add('hidden');
        document.body.classList.add('show-content');
    };
});
``` 

Archivo TXT con el Código: 
[Splash_Screen.txt](https://github.com/user-attachments/files/16946740/Splash_Screen.txt)
