### ISSUE TITLE
Mejoras de la página de Eventos en el Branch "pagina-de-eventos"

### ISSUE THREAD

**Issue by HenryRA07** [HenryRA07/Proyecto-WebSite-News#3]
## Tareas

- [x] Agregar secciones o section
- [x] Dar estilo a las secciones
- [x] Arreglar estilo del título y su texto 

## Agregar secciones o section
![image](https://github.com/user-attachments/assets/93e539c1-48d5-4a77-be19-81992779e93b)

> Para dar coherencia al código se ha decidido colocar todos los contenidos divido por secciones en la etiqueta section otorgándole una clase según sea su contenido, luego dar estilos según el WireFrame

> Las propiedades de las secciones son fijas todas van a contener el mismo estilo

```css
nombre-section {
    background-color: #fff;
    border: 1px solid #a3a2a2;
    border-radius: 10px;
    margin: 10px;
    box-shadow: 0 4px 8px #000;
    display: flex;
}
```
