### ISSUE TITLE
Efecto de selección en página de Eventos

### ISSUE THREAD

**Issue by HenryRA07** [HenryRA07/Proyecto-WebSite-News#6]
Codigo:
```css
.novedad {
    background-color: #ffffff;
    border: 1px solid #ddd;
    border-radius: 8px;
    padding: 15px;
    width: 25%;
    height: auto;
    box-shadow: 0 4px 8px #000;
    transition: all 400ms ease-out; /*Esto es lo que cambia*/
}

    .novedad:hover {
        box-shadow: 5px 4px 15px #000;
        transform: translateY(-3%);
    }

```
