### ISSUE TITLE
Ventana Emergente

### ISSUE THREAD

**Issue by HenryRA07** [HenryRA07/Proyecto-WebSite-News#7]
## Estructura para Html:
```html
<a href="#" class="open-modal" 
                       data-title="Diseño Gráfico" 
                       data-content="Detalles sobre 'La oscuridad del dinero'. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugit placeat soluta praesentium doloremque quaerat quos voluptatum harum, itaque voluptate ipsum voluptates omnis tempore obcaecati nemo exercitationem aut tempora quidem laborum?
                       Quae minus ipsam sunt incidunt tempore libero. Quos vel architecto sed adipisci, doloribus asperiores reprehenderit dignissimos cupiditate placeat necessitatibus quibusdam quae sint perferendis at temporibus unde ab perspiciatis. Accusamus, dolor."
                       data-image="/descarga.jpeg">Leer Más</a>
``` 
### Modal
```html
<!-- Modal -->
    <div id="modal" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <h2 id="modal-title"></h2>
            <img id="modal-image" src="" alt="Imagen relacionada" style="max-width: 100%; border-radius: 10px;"/>
            <p id="modal-content"></p>
        </div>
    </div>
``` 
## Estructura CSS:
```css
a {
    color: #007BFF;
    text-decoration: none;
    cursor: pointer;
}

/* Estilos de la ventana modal */
.modal {
    display: none; /* Oculto por defecto */
    position: fixed;
    z-index: 1;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    overflow: auto;
    background-color: rgba(0, 0, 0, 0.4); /* Fondo oscuro */
}

.modal-content {
    background-color: #fff;
    margin: 15% auto;
    padding: 20px;
    border: 1px solid #888;
    width: 80%;
    max-width: 500px;
    border-radius: 10px;
    text-align: center;
}

.close {
    color: #aaa;
    float: right;
    font-size: 28px;
    font-weight: bold;
    cursor: pointer;
}

.close:hover,
.close:focus {
    color: #000;
}
``` 

## Estructura JS:
```javascript
// Obtener el modal
var modal = document.getElementById("modal");

// Obtener elementos dentro del modal
var modalTitle = document.getElementById("modal-title");
var modalContent = document.getElementById("modal-content");
var modalImage = document.getElementById("modal-image");

// Obtener el botón de cierre
var closeBtn = document.getElementsByClassName("close")[0];

// Obtener todos los enlaces que abren el modal
var openModalLinks = document.getElementsByClassName("open-modal");

// Función para abrir el modal
function openModal(event) {
    event.preventDefault(); // Prevenir la acción por defecto del enlace
    var title = this.getAttribute("data-title");
    var content = this.getAttribute("data-content");
    var image = this.getAttribute("data-image");

    modalTitle.textContent = title;
    modalContent.textContent = content;
    modalImage.src = image;

    modal.style.display = "block";
}

// Asignar la función de abrir modal a todos los enlaces
for (var i = 0; i < openModalLinks.length; i++) {
    openModalLinks[i].addEventListener("click", openModal);
}

// Función para cerrar el modal
closeBtn.onclick = function() {
    modal.style.display = "none";
}

// Cerrar el modal si se hace clic fuera del contenido
window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
}
```
